import { EMAIL_PALETTE, escapeHtml } from '../mail/templates/layout';
import type { MailBody } from '../mail/types';
import type { ReportResult, ReportTable } from './types';
import { windowLabel } from './window';

/**
 * Rapor digest'i de e-posta HTML'idir: layout.ts'in kurallarının aynısı —
 * tablo tabanlı yerleşim, bütün CSS satır içi, `<style>` yok, web-safe font,
 * `border="0"` her tabloda (Outlook 2512 kenarlık bug'ı). Gmail clipping'e
 * karşı satır tavanı: digest tabloda en çok DIGEST_TABLE_MAX_ROWS satır
 * gösterilir, kalanına not düşülür; CSV eki daima tamdır.
 */
export const DIGEST_TABLE_MAX_ROWS = 30;

const { font: FONT, ink: INK, muted: MUTED, line: LINE, paper: PAPER } = EMAIL_PALETTE;

export function formatCents(cents: number, currency: string): string {
  return `${(cents / 100).toFixed(2)} ${currency}`;
}

function sectionHtml(report: ReportResult): string {
  return report.sections
    .map(
      (s) => `<tr><td style="padding:20px 32px 0 32px;font:700 15px/1.3 ${FONT};color:${INK};">${escapeHtml(s.heading)}</td></tr>
<tr><td style="padding:8px 32px 0 32px;">
<table border="0" cellpadding="0" cellspacing="0" role="presentation" width="100%" style="border:none;">
${s.items
  .map(
    (i) => `<tr>
<td style="padding:4px 0;font:400 14px/1.5 ${FONT};color:${MUTED};">${escapeHtml(i.label)}</td>
<td align="right" style="padding:4px 0;font:700 14px/1.5 ${FONT};color:${INK};">${escapeHtml(i.value)}</td>
</tr>`,
  )
  .join('')}
</table>
</td></tr>`,
    )
    .join('');
}

function tableHtml(table: ReportTable): string {
  const shown = table.rows.slice(0, DIGEST_TABLE_MAX_ROWS);
  const hidden = table.rows.length - shown.length;

  const head = table.columns
    .map(
      (c) =>
        `<td style="padding:6px 8px;font:700 12px/1.4 ${FONT};color:${MUTED};border-bottom:1px solid ${LINE};">${escapeHtml(c)}</td>`,
    )
    .join('');
  const body = shown
    .map(
      (row) =>
        `<tr>${row
          .map(
            (cell) =>
              `<td style="padding:6px 8px;font:400 13px/1.4 ${FONT};color:${INK};border-bottom:1px solid ${LINE};">${escapeHtml(String(cell))}</td>`,
          )
          .join('')}</tr>`,
    )
    .join('');
  const note =
    hidden > 0
      ? `<tr><td colspan="${table.columns.length}" style="padding:8px;font:400 12px/1.4 ${FONT};color:${MUTED};">+${hidden} more rows in the CSV attachment.</td></tr>`
      : '';

  return `<tr><td style="padding:20px 32px 0 32px;">
<table border="0" cellpadding="0" cellspacing="0" role="presentation" width="100%" style="border:none;">
<tr>${head}</tr>${body}${note}
</table>
</td></tr>`;
}

export function renderDigest(report: ReportResult): MailBody {
  const label = windowLabel(report.window);
  const subject = `[Mailmyra] ${report.title} — ${label}`;

  const html = `<!doctype html>
<html lang="en"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(report.title)}</title>
</head><body style="margin:0;padding:0;background-color:${PAPER};">
<table border="0" cellpadding="0" cellspacing="0" role="presentation" width="100%" style="background-color:${PAPER};margin:0;padding:0;border:none;">
<tr><td align="center" style="padding:32px 16px;">
<table border="0" cellpadding="0" cellspacing="0" role="presentation" width="600" style="width:100%;max-width:600px;background-color:#ffffff;border:1px solid ${LINE};">
<tr><td style="padding:28px 32px 0 32px;font:700 18px/1.2 ${FONT};color:${INK};letter-spacing:-0.01em;">Mailmyra</td></tr>
<tr><td style="padding:20px 32px 0 32px;font:700 24px/1.3 ${FONT};color:${INK};">${escapeHtml(report.title)}</td></tr>
<tr><td style="padding:4px 32px 0 32px;font:400 13px/1.6 ${FONT};color:${MUTED};">${escapeHtml(label)}</td></tr>
${sectionHtml(report)}
${report.table ? tableHtml(report.table) : ''}
<tr><td style="padding:24px 32px 28px 32px;font:400 13px/1.6 ${FONT};color:${MUTED};border-top:1px solid ${LINE};">Automated staff report. Generated by the Mailmyra report runner.</td></tr>
</table>
</td></tr>
</table>
</body></html>`;

  const lines = [`${report.title} — ${label}`, ''];
  for (const s of report.sections) {
    lines.push(s.heading);
    for (const i of s.items) lines.push(`  ${i.label}: ${i.value}`);
    lines.push('');
  }
  if (report.table) lines.push(`Table: ${report.table.rows.length} rows (see the panel or the CSV attachment).`, '');

  return { subject, html, text: [...lines, '— Mailmyra'].join('\n') };
}

export function renderCsv(table: ReportTable): string {
  const cell = (v: string | number): string => {
    const s = String(v);
    return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
  };
  const line = (row: Array<string | number>) => row.map(cell).join(',');
  return [line(table.columns), ...table.rows.map(line)].join('\r\n') + '\r\n';
}

export function csvFilename(reportId: string, end: Date): string {
  return `${reportId}-${end.toISOString().slice(0, 10)}.csv`;
}
