import type { SupportCaseRow } from '../../(admin)/support-operations-model';
import { productPreviewNow } from './product-fixtures';

const hour = 3_600_000;
const isoHour = (offset: number) => new Date(productPreviewNow + offset * hour).toISOString();

export const supportPreviewCases: SupportCaseRow[] = [
  { id: 'c1', reference: 'MM-2048', subject: 'Outlook export opens without images', customer: 'Bristol Metalworks', requester: 'emma@bristol.example', channel: 'email', category: 'export', priority: 'urgent', status: 'escalated', owner: 'support@mailmyra.com', createdAt: isoHour(-18), updatedAt: isoHour(-1), slaDueAt: isoHour(-6), summary: 'The customer can export the signature, but image assets are not visible after installing the .htm file in Outlook Classic.' },
  { id: 'c2', reference: 'MM-2047', subject: 'Annual invoice seat count review', customer: 'Harbor & Lane Agency', requester: 'finance@harborlane.example', channel: 'form', category: 'billing', priority: 'high', status: 'open', owner: 'billing@mailmyra.com', createdAt: isoHour(-9), updatedAt: isoHour(-2), slaDueAt: isoHour(2), summary: 'Finance wants the active sender count confirmed against the annual invoice before completing the bank transfer.' },
  { id: 'c3', reference: 'MM-2046', subject: 'Invite link has expired', customer: 'Quiet Coast Consulting', requester: 'hello@quietcoast.example', channel: 'email', category: 'access', priority: 'normal', status: 'waiting_customer', owner: 'support@mailmyra.com', createdAt: isoHour(-12), updatedAt: isoHour(-4), slaDueAt: isoHour(8), summary: 'A workspace owner reports that a pending member can no longer use the original invitation link.' },
  { id: 'c4', reference: 'MM-2045', subject: 'First signature needs publish guidance', customer: 'Fieldnote Publishing', requester: 'ops@fieldnote.example', channel: 'form', category: 'builder', priority: 'normal', status: 'open', owner: null, createdAt: isoHour(-5), updatedAt: isoHour(-3), slaDueAt: isoHour(15), summary: 'The team finished its first signature and needs help understanding the sender publish and export sequence.' },
  { id: 'c5', reference: 'MM-2044', subject: 'Company name correction', customer: 'Northwind Studio', requester: 'admin@northwind.example', channel: 'staff', category: 'account', priority: 'low', status: 'resolved', owner: 'support@mailmyra.com', createdAt: isoHour(-72), updatedAt: isoHour(-26), slaDueAt: isoHour(-48), summary: 'The customer requested a correction to its workspace display name after identity verification.' },
  { id: 'c6', reference: 'MM-2043', subject: 'Rich HTML copy loses spacing', customer: 'Copperline Systems', requester: 'brand@copperline.example', channel: 'email', category: 'export', priority: 'high', status: 'resolved', owner: 'support@mailmyra.com', createdAt: isoHour(-110), updatedAt: isoHour(-80), slaDueAt: isoHour(-96), summary: 'The customer reported spacing differences after pasting rich HTML into a desktop email client.' },
];
